name: Release

on:
  push:
    branches:
    - master

jobs:
  build_back:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build back image
      run: docker build -t igorkamyshev/checkmoney-back -f Dockerfile-back .
    - name: Login to Dockerhub
      run: echo "$PASSWORD" | docker login --username igorkamyshev --password-stdin
      env:
        PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push back image
      run: docker push igorkamyshev/checkmoney-back
  deploy:
    runs-on: ubuntu-latest
    needs: [build_back]
    steps:
    - name: Deploy on server
      uses: maddox/actions/ssh@064c408aac15c33fbdeb1cee155a529d6fbb13ff
      env:
        HOST: ${{ secrets.HOST }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
        USER: ${{ secrets.USER }}
      with:
        args: cd /root/web/checkmoney && docker-compose pull && docker-compose down && docker-compose up -d && docker-compose run back yarn evolutions:run && docker image prune -f
